#!/bin/bash

MUSICFOLDER=/music
PLAYLIST=background-music.m3u8

while true; do

    MP3=$(grep -vP "#EXT" $MUSICFOLDER/$PLAYLIST | grep -P "\.mp3$" | shuf -n 1 | tr '\' '/')
    if [ ! -e "$MUSICFOLDER/$MP3" ]; then
        echo "$MP3 doesn't exist! Messing with it"
	MP3=$(grep -oP "`basename $MUSICFOLDER`/.+")
    fi

    echo "Playing $MP3"

    mpg123 --rva-mix "$MUSICFOLDER/$MP3"

done
