#!/bin/zsh

VARRUN=/var/run/bgm
VARLIB=/var/lib/bgm
MUSICFOLDER=/music
LOG=/var/log/bgm.log
PLAYLISTS=$VARLIB/playlists
QUEUE=$VARRUN/queue
DEFAULTPLAYLIST=background-music.m3u8


case "$1" in
    now)
	MP3LINE=$(<$VARRUN/current-song)
	id3 -l -R "${MP3LINE% #*}"
	exit 0
	;;
    scrobble)
	if [ ! -e "$VARLIB/subsonic" ]; then
	    echo "You must specify subsonic connection details in $VARLIB/subsonic like so:"
	    echo "<host with url scheme> <user> <pass>"
	    echo ""
	    echo "e.g. https://my-subsonic-server bgm coolpassword"
	    exit 0
	fi
	if [ ! -e "$VARRUN/last-scrobbled" ]; then
	    touch "$VARRUN/last-scrobbled"
	fi
        SUBSONIC=$(<$VARLIB/subsonic)
	HOST=$(echo $SUBSONIC | awk '{ print $1 }')
	UNAME=$(echo $SUBSONIC | awk '{ print $2 }')
	PASS=$(echo $SUBSONIC | awk '{ print $3 }')
	LASTSCROBBLED=$(<$VARRUN/last-scrobbled)
	MP3=$(<$VARRUN/current-song)
	if [ "$MP3" != "$LASTSCROBBLED" ]; then
	    curl "$HOST/rest/scrobble.view?u=$UNAME&p=$PASS&c=`hostname -s`&v=1.12.0&id=${MP3##*#}"
	    echo "$MP3" > "$VARRUN/last-scrobbled"
	fi
	;;
    start)
	# pre flight checks

	if [ ! -e $PLAYLISTS/$DEFAULTPLAYLIST ]; then
	    echo "please make $DEFAULTPLAYLIST"
	    exit 1
	fi


	if [ ! -e $VARRUN ]; then
	    mkdir $VARRUN
	    chown www-data:www-data $VARRUN
	fi

	if [ ! -e $VARRUN/playlist ]; then
	    touch $VARRUN/playlist
	    chown www-data:www-data $VARRUN/playlist
	fi

	if [ ! -e $QUEUE ]; then
	    mkfifo $QUEUE
	    chown www-data:www-data $QUEUE
	fi


	exec 7<>$QUEUE

	while true; do


	echo "Playing $MP3 from the queue" | tee $LOG

	    if read -t 0.25 FILE <&7 ; then

		MP3=`echo -n "$FILE" | sed -e 's/[[:space:]]*$//' | tr '\\' '/'`
		MP3LINE="$MP3"
		if [ ! -e "$MP3" ]; then
		    echo "$MP3 doesn't exist! Prepending $MUSICFOLDER"
		    MP3=$MUSICFOLDER/$MP3
		fi
		if [ ! -e "$MP3" ]; then
		    echo "$MP3 doesn't exist! Messing with it"
		    MP3=$(grep -oP "`basename $MUSICFOLDER`/.+")
		fi

		echo "Playing $MP3 from the queue" | tee -a $LOG

	    else

		PLAYLIST=$(head -n 1 $VARRUN/playlist).m3u8
		if [ $? -ne 0 ]; then
		    PLAYLIST=$DEFAULTPLAYLIST
		fi

		if [ ! -e $PLAYLISTS/$PLAYLIST ] ; then
		    PLAYLIST=$DEFAULTPLAYLIST
		fi

		MP3LINE=$(grep -vP "#EXT" $PLAYLISTS/$PLAYLIST | grep -P "\.mp3" | shuf -n 1 | tr '\\' '/')
		MP3=${MP3LINE% #*}
		if [ ! -e "$MP3" ]; then
		    echo "$MP3 doesn't exist! Prepending $MUSICFOLDER"
		    MP3=$MUSICFOLDER/$MP3
		fi
		if [ ! -e "$MP3" ]; then
		    echo "$MP3 doesn't exist! Messing with it"
		    MP3=$(grep -oP "`basename $MUSICFOLDER`/.+")
		fi

		echo "Playing $MP3 from $PLAYLIST" | tee -a $LOG
	    fi

	    echo "$MP3LINE" > $VARRUN/current-song
	    bgm scrobble

	    mpg123 --rva-mix "$MP3"

	done
	;;
esac
