#!/bin/zsh

VARRUN=/var/run/bgm
VARLIB=/var/lib/bgm
MUSICFOLDER=/music
LOG=/var/log/bgm.log
PLAYLISTS=$VARLIB/playlists
QUEUE=$VARRUN/queue
DEFAULTPLAYLIST=background-music.m3u8


case "$1" in
    now)
	id3 -l -R "$(<$VARRUN/current-song)"
	exit 0
	;;

    start)
	# pre flight checks

	if [ ! -e $PLAYLISTS/$DEFAULTPLAYLIST ]; then
	    echo "please make $DEFAULTPLAYLIST"
	    exit 1
	fi


	if [ ! -e $VARRUN ]; then
	    mkdir $VARRUN
	    chown www-data:www-data $VARRUN
	fi

	if [ ! -e $VARRUN/playlist ]; then
	    touch $VARRUN/playlist
	    chown www-data:www-data $VARRUN/playlist
	fi

	if [ ! -e $QUEUE ]; then
	    mkfifo $QUEUE
	    chown www-data:www-data $QUEUE
	fi


	exec 7<>$QUEUE

	while true; do


	echo "Playing $MP3 from the queue" | tee $LOG

	    if read -t 0.25 FILE <&7 ; then

		MP3=`echo -n "$FILE" | sed -e 's/[[:space:]]*$//' | tr '\\' '/'`
		if [ ! -e "$MP3" ]; then
		    echo "$MP3 doesn't exist! Prepending $MUSICFOLDER"
		    MP3=$MUSICFOLDER/$MP3
		fi
		if [ ! -e "$MP3" ]; then
		    echo "$MP3 doesn't exist! Messing with it"
		    MP3=$(grep -oP "`basename $MUSICFOLDER`/.+")
		fi

		echo "Playing $MP3 from the queue" | tee -a $LOG

	    else

		PLAYLIST=$(head -n 1 $VARRUN/playlist).m3u8
		if [ $? -ne 0 ]; then
		    PLAYLIST=$DEFAULTPLAYLIST
		fi

		if [ ! -e $PLAYLISTS/$PLAYLIST ] ; then
		    PLAYLIST=$DEFAULTPLAYLIST
		fi

		MP3=$(grep -vP "#EXT" $PLAYLISTS/$PLAYLIST | grep -P "\.mp3$" | shuf -n 1 | tr '\\' '/')
		if [ ! -e "$MP3" ]; then
		    echo "$MP3 doesn't exist! Prepending $MUSICFOLDER"
		    MP3=$MUSICFOLDER/$MP3
		fi
		if [ ! -e "$MP3" ]; then
		    echo "$MP3 doesn't exist! Messing with it"
		    MP3=$(grep -oP "`basename $MUSICFOLDER`/.+")
		fi

		echo "Playing $MP3 from $PLAYLIST" | tee -a $LOG
	    fi

	    echo "$MP3" > $VARRUN/current-song

	    mpg123 --rva-mix "$MP3"

	done
	;;
esac
